apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-express
  labels:
    app: nodejs-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-express
  template:
    metadata:
      labels:
        app: nodejs-express
    spec:
      containers:
      - name: nodejs-express
        image: manfredi00/nodejsexpress-nodeapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/testdb"
        - name: KEYCLOAK_REALM
          value: "prova"
        - name: KEYCLOAK_CLIENT
          value: "prova-client"
        - name: KEYCLOAK_URL
          value: "http://localhost:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-express-service
spec:
  type: NodePort
  selector:
    app: nodejs-express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
