apiVersion: apps/v1
kind: Deployment
metadata:
  name: softwarevoti-angular-app
  labels:
    app: softwarevoti-angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softwarevoti-angular-app
  template:
    metadata:
      labels:
        app: softwarevoti-angular-app
    spec:
      containers:
      - name: softwarevoti-angular-app
        image: barrovecchio04/softwarevoti-angular-app
        ports:
        - containerPort: 4200
        env:
        - name: apiport
          value: "30080"
        - name: NODE_ENV
          value: "development"
        - name: production
          value: "false"
        - name: clientsecret
          value: "ltucFoAMhQZRHXw2yw5EASPbcmz0KF0E"
        - name: ClientId
          value: "prova-client"
        - name: keycloakUrl
          value: "http://172.25.7.58:30230"
        - name: redirectUri
          value: "http://172.25.7.58:30021"
        - name: Scope
          value: "openid profile email"
        - name: TokenEndpoint
          value: "http://172.25.7.58:30230/realms/prova/protocol/openid-connect/token"
        - name: realm
          value: "prova"
---
apiVersion: v1
kind: Service
metadata:
  name: softwarevoti-angular-app-service
spec:
  type: NodePort
  selector:
    app: softwarevoti-angular-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30021

