version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: my-mongo
    networks:
      - my_custom_network
    # Porta mappata solo se vuoi accedere da host
    # ports:
    #   - "27017:27017"

  nodeapp:
    build: .
    container_name: nodejs-express
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/testdb
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
